/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  PeckotMC: [
    {
      type: 'autogenerated',
      dirName: 'PeckotMC',
    },
  ],
  docs: [
    'index',
    'about',
    {
      type: 'category',
      label: '项目列表',
      link: {
        type: 'generated-index',
        title: '项目列表',
        description: '这里列举了 Peckot Studios 的所有项目',
        slug: '/projects',
      },
      items: [
        {
          type: 'link',
          label: 'PeckotMC 游戏服务器',
          href: '/docs/PeckotMC',
        },
        {
          type: 'link',
          label: 'AuroraBot 机器人框架',
          href: '/docs/AuroraBot',
        },
      ],
    },
  ],
};

module.exports = sidebars;
